version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - JUPYTER_TOKEN=hi
    ports:
      - "8888:8888"
      - "5000:5000"
    command: >
      sh -c "pwd &&
      python3 app.py"
#      jupyter notebook --ip 0.0.0.0 --port 8888 --allow-root &&
